package com.record.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.record.moudle.entity.LawCase;
import com.record.moudle.entity.User;

import com.record.dao.LawCaseDao;
import com.record.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lawCaseDaoConfig;
    private final DaoConfig userDaoConfig;

    private final LawCaseDao lawCaseDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lawCaseDaoConfig = daoConfigMap.get(LawCaseDao.class).clone();
        lawCaseDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        lawCaseDao = new LawCaseDao(lawCaseDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(LawCase.class, lawCaseDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        lawCaseDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public LawCaseDao getLawCaseDao() {
        return lawCaseDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
